name: Extract SongList
on:
  # schedule:
  #   - cron: '55 8 * * *' #大约每日17点05执行任务(gh服务器延迟问题)
  # watch:
  #     types: [started]
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHONIOENCODING: utf-8

# Allow Release
permissions: write-all

jobs:
  build:
    name: 'Extract SongList Operations'
    runs-on: "windows-latest"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout private repo
        uses: actions/checkout@v2

      - name: Setup Extractor  
        run: |
          pip3 install -r requirements.txt
        shell: bash  

      - name: Execute Downloader
        id: operation
        run:  python3 DynamixAssets.py
    
      - name: commit
        env:
          useremail: ${{ secrets.GH_EMAIL }}
        run: |
          git config --global user.email useremail
          git config --global user.name GithubActionBot
          git add .
          git commit -m "仓库更新" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_AUTH_TOKEN }}